const mongoose = require('mongoose');

const appControllerSchema = new mongoose.Schema({
  id: { type: String },
  app_id: { type: String },
  imp_notice_on_home: { type: String },
  diamond_con_rate: { type: Number },
  admin_key: { type: String },
  app_name: { type: String },
  admin_status: { type: String },
  theme_color: { type: String },
  wallet: { type: Boolean, default: false },
  history: { type: Boolean, default: false },
  transaction: { type: Boolean, default: false },
  online_deposit: { type: Boolean, default: false },
  whatsapp: { type: String },
  redeem: { type: Boolean, default: false },
  min_deposit: { type: Number },
  max_deposit: { type: Number },
  min_redeem: { type: Number },
  HarufMax: { type: Number },
  HarufMin: { type: Number },
  jodi_max: { type: Number },
  jodi_min: { type: Number },
  crossingMin: { type: Number },
  crossingMax: { type: Number },
  withdraw_open_time: { type: String },
  withdraw_close_time: { type: String },
  upiId: { type: String },
  rz_key: { type: String },
  rz_secrate: { type: String },
  mrCode: { type: String },
  messagePayment: { type: String },
  after_in_playTimeMessage: { type: String },
  dep_pp: { type: Number },
  dep_gp: { type: Number },
  dep_pytm: { type: Number },
  dep_oth: { type: Number },
  with_pytm: { type: Number },
  with_pp: { type: Number },
  with_gp: { type: Number },
  app_version: { type: String },
  force_update: { type: Boolean, default: false },
  is_app_maintainance: { type: Boolean, default: false },
  maintainance_image: { type: String },
  maintainance_message: { type: String },
  maintainance_till_date: { type: Date },
  fcm_key: { type: String },
  pft_rto: { type: Number },
  num_range: { type: String },
  result_on_off: { type: Boolean, default: false },
  is_paly_on_off: { type: Boolean, default: false },
  offers: { type: String },
  reffral: { type: Boolean, default: false },
  renk_system: { type: Boolean, default: false },
  reffral_sender_value: { type: Number },
  reffral_reg_value: { type: Number },
  app_status: { type: String },
  perday_visit_by_user: { type: Number },
  about: { type: String },
  blog: { type: String },
  privacy_policy: { type: String },
  tutorial_video: { type: String },
  how_to_play: { type: String },
  nav_chart: { type: String },
  admin_contact_mob: { type: String },
  dep_message: { type: String },
  call_enable: { type: Boolean, default: false },
  oth_link: { type: String },
  ref_comm: { type: Number },
  reffer_link: { type: String },
  version: { type: String },
  withdraw_otp: { type: Boolean, default: false },
  is_app_mentinance3: { type: Boolean, default: false },
  is_app_maintenance5: { type: Boolean, default: false },
  min_jodi: { type: Number }
}, { collection: 'app_controller' });

module.exports = mongoose.model('appController', appControllerSchema);
