const mongoose = require('mongoose');
const deleted_betSchema = new mongoose.Schema({
  id: { type: Number },
  game_type: { type: Number },
  app_id: { type: String },
  admin_key: { type: String },
  user_id: { type: String },
  transaction_id: { type: String },
  tr_nature: { type: String },
  slot_id: { type: Number,default:null },
  win_value: { type: Number,default:0 },
  tr_value: { type: Number},
  tr_value_updated: { type: Number},
  value_update_by: { type: String},
  tr_value_type: { type: String},
  date: { type: String},
  date_time: { type: String},
  tr_remark: { type: String},
  tr_status: { type: String},
  table_id: { type: String,default:null},
  is_win: { type: String,default:0},
  is_result_declared: { type: String,default:0},
  pred_num: { type: String,default:null},
  is_deleted: { type: String,default:0},
  win_bet_amt_not_use: { type: String,default:0},
  result_date: { type: String,default:null},
  payout_by: { type: Number},
  d_type: { type: String},
  t_mob: { type: String,default:null},
  upi_id: { type: String,default:null},
  is_payout_pending: { type: String,default:0},
  is_transfer: { type: String,default:0},
  transfer_user_id: { type: String,default:null},
  upi_txn_id: { type: String},
  is_payout_cleared: { type: Number,default:0},
  uniquid: { type: String,default:null},
  dateTime: { type: Number,default:null},
  payinType: { type: String},
  betExpTime: { type: String,default:null},
  betTime: { type: String,default:null},
  is_checked: { type: Number},
  checked_by: { type: Number,default:null},
  deleted_by: { type: String,default:null},
  betLimitStatus: { type: Number,default:null},
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
}, { collection: 'deleted_bet' });
module.exports = mongoose.model('Deleted_bet', deleted_betSchema);

