const mongoose = require("mongoose");
const point_tableSchema = new mongoose.Schema(
  {
    id: { type: Number },
    game_type: { type: Number, Default: 1 },
    app_id: { type: String },
    admin_key: { type: String },
    user_id: { type: String },
    transaction_id: { type: String },
    tr_nature: { type: String },
    slot_id: { type: Number, Default: null },
    win_value: { type: Number, Default: 0 },
    tr_value: { type: Number },
    tr_value_updated: { type: Number },
    value_update_by: { type: String },
    tr_value_type: { type: String },
    date: { type: String, default: Date.now },
    date_time: { type: String },
    tr_remark: { type: String },
    tr_status: { type: String },
    table_id: { type: String, Default: null },
    is_win: { type: String, Default: 0 },
    is_result_declared: { type: String, Default: 0 },
    pred_num: { type: String, Default: null },
    is_deleted: { type: String, Default: 0 },
    win_bet_amt_not_use: { type: Number, Default: 0 },
    result_date: { type: String, Default: 0 },
    payout_by: { type: Number, Default: 0 },
    d_type: { type: String },
    t_mob: { type: Number, Default: null },
    upi_id: { type: String, Default: null },
    is_payout_pending: { type: Number, Default: 0 },
    is_transfer: { type: Number, Default: 0 },
    transfer_user_id: { type: String, Default: null },
    upi_txn_id: { type: String },
    is_payout_cleared: { type: Number, Default: 0 },
    uniquid: { type: Number, Default: null },
    dateTime: { type: Number, Default: null },
    payinType: { type: String },
    betExpTime: { type: String, Default: null },
    betTime: { type: String, Default: null },
    is_checked: { type: String, Default: 1 },
    betLimitStatus: { type: String, Default: 0 },
    tr_device: { type: String },
    device_id: { type: String },
    device_type: { type: String },
    checked_by: { type: String },
    account_no: { type: Number, Default: null},
    ifsc_code: { type: String, Default: null},
    withdrawType: { type: String, default: 'bank' },
    transferByMob: { type: String, Default: null },
    transferByName: { type: String, Default: null },
    created_at: { type: Date, default: Date.now },
    updated_at: { type: Date, default: Date.now },
    login_url: { type: String, default: null },
  },
  { collection: "point_table" }
);
module.exports = mongoose.model("PointTable", point_tableSchema);
