const mongoose = require("mongoose");

const bookSchema = new mongoose.Schema(
  {
    id: { type: Number },
    user_id: { type: String },
    upiid: { type: String, default: null },
    app_id: { type: String },
    FullName: { type: String },
    email: { type: String },
    dob: { type: String },
    mob: { type: String },
    image: { type: String, default: null },
    note: { type: String, default: null },
    us_pass: { type: String, default: null },
    us_gender: { type: String, default: null },
    credit: { type: Number, default: 0 },
    win_amount: { type: Number, default: 0 },
    bonus_diamonds: { type: Number, default: 0 },
    ref_code: { type: String, default: null },
    ref_by: { type: String, default: null },
    is_ref_enabled: { type: Number, default: 1 },
    ref_bonous: { type: Number, default: 0 },
    total_played: { type: String, default: 0 },
    total_bonus: { type: Number, default: 0 },
    my_played: { type: Number, default: 0 },
    dev_model: { type: String },
    dev_name: { type: String },
    device_id: { type: String },
    user_status: { type: Number, default: 1 },
    reg_date: { type: String, default: null },
    reg_time: { type: String, default: null },
    last_login: { type: String, default: null },
    last_active: { type: String, default: null },
    created_at: { type: Date, default: Date.now },
    updated_at: { type: Date, default: Date.now },
    prev_pass: { type: String, default: null },
    is_child: { type: Number, default: 0 },
    device_token: { type: String },
    commission: { type: Number, default: 0 },
    last_seen: { type: Date },
    user_type: { type: String, default: "normal" },
    child_count: { type: Number, default: null },
    is_kyc: { type: Number, default: 1 },
    game_win: { type: Number, default: 0 },
    h_win: { type: Number, default: 0 },
    version: { type: String, default: null },
    login_url: { type: String, default: null },
    game_host: { type: Number, default: 0 },
    user_from: { type: String },
    login_token: { type: String },
    last_seen_date_time: { type: String, default: null },
    is_login: { type: Number, default: 0 },
    is_logout: { type: Number, default: 0 },
    is_bonus: { type: Number, default: 0 },
    lat: { type: String, default: null },
    long: { type: String, default: null },
    token: { type: String, default: null },
  },
  { collection: "us_reg_tbl" }
);

module.exports = mongoose.model("User", bookSchema);
